const CATEGORY_META = {
  "Nature": { color: "#2F7D58" },
  "Animals": { color: "#20858A" },
  "Science / Space": { color: "#5365B5" },
  "History": { color: "#A85C44" },
  "Museums": { color: "#7A5AA6" },
  "Weird / Roadside": { color: "#C15478" },
  "Arts & Culture": { color: "#B78027" },
  "Engineering / Architecture": { color: "#4C6F91" },
  "Scenic Places": { color: "#9D6B55" }
};

const ATTRACTIONS = [
  {
    id: "hopewell-rocks",
    name: "Hopewell Rocks",
    lat: 45.8226,
    lng: -64.5768,
    region: "New Brunswick",
    country: "Canada",
    categories: ["Nature", "Scenic Places"],
    primaryCategory: "Nature",
    description: "Walk on the ocean floor beneath enormous sea stacks shaped by the Bay of Fundy tides.",
    website: "https://www.thehopewellrocks.ca/",
    visitLength: "2–4 hours",
    cost: "Paid admission",
    setting: "Mostly outdoor",
    seasonal: "Seasonal access varies",
    accessibility: "Partial accessibility",
    editorial: "Worth a detour"
  },
  {
    id: "parc-bic",
    name: "Parc national du Bic",
    lat: 48.3554,
    lng: -68.7828,
    region: "Québec",
    country: "Canada",
    categories: ["Nature", "Scenic Places"],
    primaryCategory: "Scenic Places",
    description: "A rugged St. Lawrence shoreline of coves, headlands, forest trails and famously beautiful sunsets.",
    website: "https://www.sepaq.com/pq/bic/",
    visitLength: "Half day–full day",
    cost: "Paid admission",
    setting: "Outdoor",
    seasonal: "Best explored in warmer months",
    accessibility: "Accessibility varies by trail",
    editorial: "Worth building a trip around"
  },
  {
    id: "montreal-biosphere",
    name: "Montréal Biosphère",
    lat: 45.5147,
    lng: -73.5318,
    region: "Québec",
    country: "Canada",
    categories: ["Science / Space", "Engineering / Architecture", "Museums"],
    primaryCategory: "Engineering / Architecture",
    description: "Environmental exhibits inside Buckminster Fuller’s striking geodesic dome from Expo 67.",
    website: "https://espacepourlavie.ca/en/biosphere",
    visitLength: "1–2 hours",
    cost: "Paid admission",
    setting: "Indoor",
    seasonal: "Year-round",
    accessibility: "Generally accessible",
    editorial: "Stop if you’re nearby"
  },
  {
    id: "science-north",
    name: "Science North",
    lat: 46.4703,
    lng: -80.9930,
    region: "Ontario",
    country: "Canada",
    categories: ["Science / Space", "Museums"],
    primaryCategory: "Science / Space",
    description: "A hands-on science centre built into the rocky shore of Ramsey Lake, with interactive exhibits and live science.",
    website: "https://www.sciencenorth.ca/",
    visitLength: "3–5 hours",
    cost: "Paid admission",
    setting: "Mostly indoor",
    seasonal: "Year-round",
    accessibility: "Generally accessible",
    editorial: "Worth a detour"
  },
  {
    id: "royal-tyrrell",
    name: "Royal Tyrrell Museum",
    lat: 51.4671,
    lng: -112.7080,
    region: "Alberta",
    country: "Canada",
    categories: ["Museums", "Science / Space", "History"],
    primaryCategory: "Museums",
    description: "One of the world’s great dinosaur museums, set in Alberta’s dramatic badlands fossil country.",
    website: "https://tyrrellmuseum.com/",
    visitLength: "3–5 hours",
    cost: "Paid admission",
    setting: "Mostly indoor",
    seasonal: "Year-round",
    accessibility: "Generally accessible",
    editorial: "Worth building a trip around"
  },
  {
    id: "cmhr",
    name: "Canadian Museum for Human Rights",
    lat: 49.8902,
    lng: -97.1312,
    region: "Manitoba",
    country: "Canada",
    categories: ["Museums", "History", "Engineering / Architecture"],
    primaryCategory: "History",
    description: "A major museum exploring human rights history and ideas inside one of Winnipeg’s most distinctive buildings.",
    website: "https://humanrights.ca/",
    visitLength: "3–5 hours",
    cost: "Paid admission",
    setting: "Indoor",
    seasonal: "Year-round",
    accessibility: "Strong accessibility features",
    editorial: "Worth a detour"
  },
  {
    id: "beringia-centre",
    name: "Yukon Beringia Interpretive Centre",
    lat: 60.7193,
    lng: -135.0528,
    region: "Yukon",
    country: "Canada",
    categories: ["Science / Space", "History", "Museums"],
    primaryCategory: "Science / Space",
    description: "Ice Age fossils, ancient landscapes and the human history of Beringia, told through a compact northern museum.",
    website: "https://beringia.com/",
    visitLength: "1–2 hours",
    cost: "Paid admission",
    setting: "Indoor",
    seasonal: "Hours vary seasonally",
    accessibility: "Generally accessible",
    editorial: "Worth a detour"
  },
  {
    id: "lanse-aux-meadows",
    name: "L’Anse aux Meadows",
    lat: 51.5964,
    lng: -55.5339,
    region: "Newfoundland and Labrador",
    country: "Canada",
    categories: ["History", "Scenic Places"],
    primaryCategory: "History",
    description: "The remains of an 11th-century Norse settlement on the far northern tip of Newfoundland.",
    website: "https://parks.canada.ca/lhn-nhs/nl/meadows",
    visitLength: "2–3 hours",
    cost: "Paid admission",
    setting: "Indoor + outdoor",
    seasonal: "Seasonal visitor services",
    accessibility: "Partial accessibility",
    editorial: "Worth building a trip around"
  },
  {
    id: "magnetic-hill",
    name: "Magnetic Hill",
    lat: 46.1344,
    lng: -64.8837,
    region: "New Brunswick",
    country: "Canada",
    categories: ["Weird / Roadside"],
    primaryCategory: "Weird / Roadside",
    description: "A classic roadside optical illusion where cars appear to roll uphill when placed in neutral.",
    website: "https://www.moncton.ca/magnetichill",
    visitLength: "20–40 minutes",
    cost: "Paid admission",
    setting: "Outdoor / in-car",
    seasonal: "Seasonal operation",
    accessibility: "Experienced from a vehicle",
    editorial: "Stop if you’re nearby"
  },
  {
    id: "peggys-cove",
    name: "Peggy’s Cove",
    lat: 44.4939,
    lng: -63.9177,
    region: "Nova Scotia",
    country: "Canada",
    categories: ["Scenic Places", "Arts & Culture"],
    primaryCategory: "Scenic Places",
    description: "Granite coastline, weathered fishing buildings and one of Canada’s most recognizable lighthouses.",
    website: "https://www.novascotia.com/see-do/attractions/peggys-cove/",
    visitLength: "1–2 hours",
    cost: "Free",
    setting: "Outdoor",
    seasonal: "Year-round; weather matters",
    accessibility: "Accessible viewing deck available",
    editorial: "Worth a detour"
  },
  {
    id: "kennedy-space-center",
    name: "Kennedy Space Center Visitor Complex",
    lat: 28.5233,
    lng: -80.6819,
    region: "Florida",
    country: "United States",
    categories: ["Science / Space", "Engineering / Architecture", "Museums"],
    primaryCategory: "Science / Space",
    description: "Historic launch hardware, rockets, spacecraft and the story of NASA’s human spaceflight programs.",
    website: "https://www.kennedyspacecenter.com/",
    visitLength: "Full day",
    cost: "Paid admission",
    setting: "Indoor + outdoor",
    seasonal: "Year-round",
    accessibility: "Generally accessible",
    editorial: "Worth building a trip around"
  },
  {
    id: "air-space-dc",
    name: "National Air and Space Museum",
    lat: 38.8882,
    lng: -77.0199,
    region: "Washington, DC",
    country: "United States",
    categories: ["Science / Space", "Museums", "History"],
    primaryCategory: "Museums",
    description: "Landmark aircraft and spacecraft tracing the history of flight, exploration and space science.",
    website: "https://airandspace.si.edu/",
    visitLength: "2–4 hours",
    cost: "Free",
    setting: "Indoor",
    seasonal: "Year-round",
    accessibility: "Generally accessible",
    editorial: "Worth a detour"
  },
  {
    id: "field-museum",
    name: "Field Museum",
    lat: 41.8663,
    lng: -87.6170,
    region: "Illinois",
    country: "United States",
    categories: ["Museums", "Science / Space", "History"],
    primaryCategory: "Museums",
    description: "Natural history on a grand scale, from dinosaurs and meteorites to cultures and ecosystems around the world.",
    website: "https://www.fieldmuseum.org/",
    visitLength: "3–5 hours",
    cost: "Paid admission",
    setting: "Indoor",
    seasonal: "Year-round",
    accessibility: "Generally accessible",
    editorial: "Worth a detour"
  },
  {
    id: "city-museum-stl",
    name: "City Museum",
    lat: 38.6338,
    lng: -90.2005,
    region: "Missouri",
    country: "United States",
    categories: ["Arts & Culture", "Museums", "Engineering / Architecture"],
    primaryCategory: "Arts & Culture",
    description: "A surreal, climbable maze of architectural salvage, tunnels, slides, sculpture and industrial imagination.",
    website: "https://citymuseum.org/",
    visitLength: "3–6 hours",
    cost: "Paid admission",
    setting: "Indoor + outdoor",
    seasonal: "Year-round; some areas weather-dependent",
    accessibility: "Accessibility varies greatly by area",
    editorial: "Worth building a trip around"
  },
  {
    id: "badlands-national-park",
    name: "Badlands National Park",
    lat: 43.7447,
    lng: -102.4993,
    region: "South Dakota",
    country: "United States",
    categories: ["Nature", "Scenic Places"],
    primaryCategory: "Nature",
    description: "Layered rock formations, sweeping prairie and one of the most otherworldly scenic drives in the Great Plains.",
    website: "https://www.nps.gov/badl/",
    visitLength: "Half day–full day",
    cost: "Paid park entry",
    setting: "Outdoor",
    seasonal: "Year-round; weather varies sharply",
    accessibility: "Accessible overlooks available",
    editorial: "Worth building a trip around"
  },
  {
    id: "cadillac-ranch",
    name: "Cadillac Ranch",
    lat: 35.1872,
    lng: -101.9870,
    region: "Texas",
    country: "United States",
    categories: ["Weird / Roadside", "Arts & Culture"],
    primaryCategory: "Weird / Roadside",
    description: "Ten Cadillacs buried nose-first in a field, continuously repainted by generations of visitors.",
    website: "https://www.visitamarillo.com/listing/cadillac-ranch/677/",
    visitLength: "20–45 minutes",
    cost: "Free",
    setting: "Outdoor",
    seasonal: "Year-round",
    accessibility: "Uneven field; conditions vary",
    editorial: "Stop if you’re nearby"
  },
  {
    id: "ufo-museum-roswell",
    name: "International UFO Museum and Research Center",
    lat: 33.3943,
    lng: -104.5220,
    region: "New Mexico",
    country: "United States",
    categories: ["Weird / Roadside", "Museums"],
    primaryCategory: "Weird / Roadside",
    description: "A wonderfully specific museum devoted to the Roswell incident, UFO folklore and the culture surrounding it.",
    website: "https://www.roswellufomuseum.com/",
    visitLength: "1–2 hours",
    cost: "Paid admission",
    setting: "Indoor",
    seasonal: "Year-round",
    accessibility: "Generally accessible",
    editorial: "Worth a detour"
  },
  {
    id: "monterey-bay-aquarium",
    name: "Monterey Bay Aquarium",
    lat: 36.6182,
    lng: -121.9018,
    region: "California",
    country: "United States",
    categories: ["Animals", "Science / Space", "Museums"],
    primaryCategory: "Animals",
    description: "A celebrated ocean aquarium known for kelp forest habitats, sea otters and conservation-focused exhibits.",
    website: "https://www.montereybayaquarium.org/",
    visitLength: "3–5 hours",
    cost: "Paid admission",
    setting: "Indoor",
    seasonal: "Year-round",
    accessibility: "Generally accessible",
    editorial: "Worth building a trip around"
  },
  {
    id: "mopop",
    name: "Museum of Pop Culture",
    lat: 47.6215,
    lng: -122.3481,
    region: "Washington",
    country: "United States",
    categories: ["Arts & Culture", "Museums", "Engineering / Architecture"],
    primaryCategory: "Arts & Culture",
    description: "Music, film, games and fandom inside Frank Gehry’s exuberant building beside Seattle Center.",
    website: "https://www.mopop.org/",
    visitLength: "2–4 hours",
    cost: "Paid admission",
    setting: "Indoor",
    seasonal: "Year-round",
    accessibility: "Generally accessible",
    editorial: "Worth a detour"
  }
];
